- name: Download MongoDB Exporter
  get_url:
    url: https://github.com/percona/mongodb_exporter/releases/download/v0.40.0/mongodb_exporter-0.40.0.linux-amd64.tar.gz
    dest: /tmp/mongodb_exporter.tar.gz

- name: Extract MongoDB Exporter
  unarchive:
    src: /tmp/mongodb_exporter.tar.gz
    dest: /usr/local/
    remote_src: yes

- name: Move MongoDB Exporter binary
  command: mv /usr/local/mongodb_exporter-0.40.0.linux-amd64/mongodb_exporter /usr/local/bin/mongodb_exporter
  args:
    creates: /usr/local/bin/mongodb_exporter

- name: Create systemd service for MongoDB Exporter
  copy:
    dest: /etc/systemd/system/mongodb_exporter.service
    content: |
      [Unit]
      Description=MongoDB Exporter
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/mongodb_exporter --mongodb.uri=mongodb://localhost:27017
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start MongoDB Exporter
  systemd:
    name: mongodb_exporter
    enabled: yes
    state: started
    daemon_reload: yes
