---
- name: Install MongoDB
  apt:
    name: mongodb
    state: present
    update_cache: yes

- name: Ensure MongoDB is started
  service:
    name: mongodb
    state: started
    enabled: yes
