---
- name: Configure MongoDB Server
  hosts: db
  become: yes
  roles:
    - db
    - node_exporter 

- name: Configure Web Server
  hosts: web
  become: yes
  roles:
    - web
    - node_exporter 
